TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
#DB += dbExample1.db
#DB += dbExample2.db
#DB += dbSubExample.db
#DB += user.substitutions
#DB += userHost.substitutions
#DB += hybLV.db
DB += dbHybT.db
DB += dbHybLV.db
DB += dbHybLVStat.db
DB += dbHybSwitch.db
DB += dbFebTemp.db
DB += dbSVT.db
DB += dbDpmMap.db
DB += dbDataDpm.db
DB += dbDataDpmFebNum.db
DB += dbDataDpmHybNum.db
DB += dbDataDtm.db
DB += dbFebLayer.db
DB += dbHybSync.db
#DB += dbSVTtest.db

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

